### ISSUE TITLE
Is this still worked on?

### ISSUE THREAD

**Issue by seanaguinaga** [kelvinmaues/react-hubspot-tracking-code-hook#15]
This hook is awesome!

Is this still under active development? The "Next Features" sound like things I'd need.

**Comment by kelvinmaues** [comment]
Hey @seanaguinaga thanks for reaching out.

I'm away from the development here. Feel free to fork this project, develop some features and we can release a new version against your pull request. What do you think?

**Comment by seanaguinaga** [comment]
I still need to wrap my head around the HubSpot analytics docs themselves, but yeah!

That could work!

**Comment by BilalurRehman-27** [comment]
I am using a NextJs project and I was not finding any documentation until I came across this github project and man o man did it worked. Thanks guys.

**Comment by mikelml-sendspark** [comment]
Hello my friend, sorry for dummy question, but in wich part of hubspot crm panel can i see my devlopment logs of th racking?
